/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#4cd7f6",
        "secondary-fixed": "#acedff",
        "on-secondary-fixed": "#001f26",
        "primary-container": "#4f46e5",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#57dffe",
        "secondary": "#00687a",
        "on-tertiary-container": "#67f4b7",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "inverse-primary": "#c3c0ff",
        "inverse-surface": "#213145",
        "tertiary": "#005338",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "tertiary-container": "#006e4b",
        "on-primary-container": "#dad7ff",
        "on-surface": "#0b1c30",
        "error": "#ba1a1a",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "primary-fixed": "#e2dfff",
        "on-secondary-container": "#006172",
        "surface-tint": "#4d44e3",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#004e5c",
        "outline": "#777587",
        "background": "#f8f9ff",
        "surface-container": "#e5eeff",
        "primary": "#3525cd",
        "on-primary-fixed-variant": "#3323cc",
        "on-surface-variant": "#464555"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "48px",
        "container-max": "1280px",
        "md": "24px",
        "xs": "4px",
        "sm": "12px",
        "gutter": "24px",
        "xl": "80px",
        "base": "8px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "label-sm": ["Geist"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "title-md": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "title-md": ["18px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
